Use async friendly stacktrace for exception details
Frogvall/AspNetCoreApiUtilities pull request #1
Opened 2018-07-18 12:26 UTC by mihail-yartsev

Added [AsyncFriendlyStackTrace ](https://github.com/aelij/AsyncFriendlyStackTrace) lib to format the exception messages on Development env.

When a request to a web api fails on a development environment in an async method - we get a long callstack with lots of rethrows. Instead we can get a more readable one, with async methods shown as a single line each. [Example](https://github.com/aelij/AsyncFriendlyStackTrace/blob/master/docs/Example1.md).

One more difference is that now the Detail field contains the full exception info, not only the stacktrace. This was introduced mainly because of the AsyncFriendlyStackTrace lib limitations, but it also adds more details about the exception.

2018-08-15 10:49 UTC, Frogvall requested changes
<VersionPrefix> is used instead of <Version>, see code comment

2018-08-15 10:49 UTC, Frogvall commented on src/AspNetCoreApiUtilities/AspNetCoreApiUtilities.csproj
> +    <Version>2.1.0</Version>
Please update the VersionPrefix tag, instead of providing the version tag.

2018-08-15 14:05 UTC, mihail-yartsev commented
Fixed the version tags

2018-08-16 11:24 UTC, Frogvall approved these changes

2018-08-16 11:56 UTC, merged